name: Deploy to Vultr VPS

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -o myapp
      
      - name: Debug secret presence
        run: |
          echo "Secret length: ${#VPS_SSH_KEY}"
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

      - name: Upload to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "myapp"
          target: "/home/${{ secrets.VPS_USER }}/myapp"

      - name: Restart app on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo pkill myapp || true
            sudo nohup ./myapp > output.log 2>&1 &
